In [2]:
import pandas as pd
import numpy as np

In [6]:
#reading data set
data = pd.read_csv('../Data_bases/ndtv_data_final.csv')

In [7]:
data.head()

Unnamed: 0                            Name    Brand  \
0           0  OnePlus 7T Pro McLaren Edition  OnePlus   
1           1                   Realme X2 Pro   Realme   
2           2               iPhone 11 Pro Max    Apple   
3           3                       iPhone 11    Apple   
4           4                    LG G8X ThinQ       LG   

                    Model  Battery capacity (mAh)  Screen size (inches)  \
0  7T Pro McLaren Edition                    4085                  6.67   
1                  X2 Pro                    4000                  6.50   
2       iPhone 11 Pro Max                    3969                  6.50   
3               iPhone 11                    3110                  6.10   
4               G8X ThinQ                    4000                  6.40   

  Touchscreen  Resolution x  Resolution y  Processor  ...  Rear camera  \
0         Yes          1440          3120          8  ...         48.0   
1         Yes          1080          2400          8  ...         64.0   
2         Yes          1242          2688          6  ...         12.0   
3         Yes           828          1792          6  ...         12.0   
4         Yes          1080          2340          8  ...         12.0   

   Front camera  Operating system  Wi-Fi Bluetooth  GPS Number of SIMs   3G  \
0          16.0           Android    Yes       Yes  Yes              2  Yes   
1          16.0           Android    Yes       Yes  Yes              2  Yes   
2          12.0               iOS    Yes       Yes  Yes              2  Yes   
3          12.0               iOS    Yes       Yes  Yes              2  Yes   
4          32.0           Android    Yes       Yes  Yes              1   No   

   4G/ LTE   Price  
0      Yes   58998  
1      Yes   27999  
2      Yes  106900  
3      Yes   62900  
4       No   49990  

[5 rows x 22 columns]

In [8]:
#dropping second index
data = data.drop('Unnamed: 0', axis=1)

In [9]:
cols = [] 
for col in data.columns: 
    cols.append(col.lower().replace(' ', '_')) 
data.columns = cols

data.head()

name    brand                   model  \
0  OnePlus 7T Pro McLaren Edition  OnePlus  7T Pro McLaren Edition   
1                   Realme X2 Pro   Realme                  X2 Pro   
2               iPhone 11 Pro Max    Apple       iPhone 11 Pro Max   
3                       iPhone 11    Apple               iPhone 11   
4                    LG G8X ThinQ       LG               G8X ThinQ   

   battery_capacity_(mah)  screen_size_(inches) touchscreen  resolution_x  \
0                    4085                  6.67         Yes          1440   
1                    4000                  6.50         Yes          1080   
2                    3969                  6.50         Yes          1242   
3                    3110                  6.10         Yes           828   
4                    4000                  6.40         Yes          1080   

   resolution_y  processor  ram_(mb)  ...  rear_camera  front_camera  \
0          3120          8     12000  ...         48.0          16.0   
1          2400          8      6000  ...         64.0          16.0   
2          2688          6      4000  ...         12.0          12.0   
3          1792          6      4000  ...         12.0          12.0   
4          2340          8      6000  ...         12.0          32.0   

   operating_system wi-fi bluetooth  gps number_of_sims   3g 4g/_lte   price  
0           Android   Yes       Yes  Yes              2  Yes     Yes   58998  
1           Android   Yes       Yes  Yes              2  Yes     Yes   27999  
2               iOS   Yes       Yes  Yes              2  Yes     Yes  106900  
3               iOS   Yes       Yes  Yes              2  Yes     Yes   62900  
4           Android   Yes       Yes  Yes              1   No      No   49990  

[5 rows x 21 columns]

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1359 entries, 0 to 1358
Data columns (total 21 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   name                    1359 non-null   object 
 1   brand                   1359 non-null   object 
 2   model                   1359 non-null   object 
 3   battery_capacity_(mah)  1359 non-null   int64  
 4   screen_size_(inches)    1359 non-null   float64
 5   touchscreen             1359 non-null   object 
 6   resolution_x            1359 non-null   int64  
 7   resolution_y            1359 non-null   int64  
 8   processor               1359 non-null   int64  
 9   ram_(mb)                1359 non-null   int64  
 10  internal_storage_(gb)   1359 non-null   float64
 11  rear_camera             1359 non-null   float64
 12  front_camera            1359 non-null   float64
 13  operating_system        1359 non-null   object 
 14  wi-fi                   1359 non-null   

In [11]:
#droping names column since it is only the concatenation of the model and brand
data = data.drop('name', axis=1)

Checking the unique values of each important column:

In [12]:
data['brand'].unique()

array(['OnePlus', 'Realme', 'Apple', 'LG', 'Samsung', 'Asus', 'Xiaomi',
       'Oppo', 'Huawei', 'Google', 'Nokia', 'HTC', 'Motorola', 'Honor',
       'Yu', 'Poco', 'Vivo', 'Nubia', 'Black Shark', 'Infinix', 'Lenovo',
       'Sony', 'Jio', 'Coolpad', 'Micromax', 'Smartron', 'LeEco',
       'BlackBerry', 'Gionee', 'Meizu', 'Panasonic', 'Tecno', 'InFocus',
       'Itel', '10.or', 'Lava', 'Cat', 'Lyf', 'Intex', 'Xolo', 'Acer',
       'Phicomm', 'Karbonn', 'Spice', 'iVoomi', 'Kult', 'Nuu Mobile',
       'Ziox', 'Zopo', 'ZTE', 'Onida', 'Microsoft', 'iBall', 'Mobiistar',
       'Comio', 'Videocon', 'Alcatel', 'Reach', 'Zen', 'Tambo', 'Razer',
       'Homtom', 'Lephone', 'Aqua', 'Celkon', 'Jivi', 'Billion', 'Swipe',
       'M-tech', 'Sansui', 'Zuk', 'TCL', 'mPhone', 'Blu', 'HP', 'Philips'],
      dtype=object)

In [13]:
data['battery_capacity_(mah)'].unique()

array([4085, 4000, 3969, 3110, 3800, 4300, 6000, 3765, 4065, 4045, 4200,
       3300, 3700, 2942, 2658, 3430, 2915, 3000, 5000, 3500, 3930, 1821,
       2691, 2716, 2730, 3090, 3400, 3450, 2900, 1960, 3600, 3760, 2750,
       2500, 3050, 2550, 3100, 4500, 4100, 4035, 4030, 4020, 3550, 3060,
       3260, 3750, 3730, 3410, 3200, 4350, 3340, 3080, 2700, 3520, 2000,
       5300, 4060, 3230, 3120, 3510, 2600, 2800, 4850, 1624, 4050, 2150,
       1715, 4900, 2420, 3630, 2470, 3900, 3220, 2400, 1810, 2300, 2070,
       1507, 2200, 2330, 2100, 4230, 3010, 3180, 3030, 3020, 3225, 4010,
       4550, 3055, 5100, 3150, 3075, 2610, 2850, 5020, 2230, 2390, 1900,
       1700, 1860, 1920, 2140, 1980, 2410, 2250, 2350, 1500, 1010, 2180,
       1320, 2370, 1350, 1300, 1650, 1800, 4070, 3250, 2680, 2620, 2630,
       3130, 2720, 2650, 2930, 1400, 2840, 1950, 2515, 2050, 2540, 1430,
       3140, 2880, 1200, 1540, 1450, 4120, 3950, 3046, 4380, 3315, 3285,
       2990, 3360, 3580, 1600, 2670, 1750, 2210, 24

In [14]:
data['screen_size_(inches)'].unique()

array([6.67, 6.5 , 6.1 , 6.4 , 6.55, 6.8 , 6.59, 6.39, 6.53, 6.6 , 6.3 ,
       6.47, 6.41, 5.8 , 5.5 , 6.  , 5.99, 6.28, 6.2 , 4.7 , 5.3 , 5.7 ,
       5.2 , 5.15, 5.1 , 5.4 , 6.52, 6.7 , 6.44, 6.65, 6.38, 6.08, 6.26,
       5.6 , 6.21, 6.18, 5.84, 5.86, 6.42, 6.23, 5.65, 5.98, 6.01, 5.9 ,
       5.  , 2.4 , 4.  , 5.96, 4.5 , 4.6 , 4.3 , 4.95, 4.8 , 6.35, 6.22,
       6.19, 5.45, 5.93, 4.93, 3.  , 3.1 , 3.5 , 2.6 , 3.8 , 4.2 , 5.71,
       5.47, 4.69, 2.8 , 3.7 , 3.2 , 2.44, 6.9 , 6.09, 7.3 , 5.72, 5.67,
       5.34, 2.45, 7.  ])

In [15]:
data['touchscreen'].unique()

array(['Yes', 'No'], dtype=object)

In [16]:
data['resolution_x'].unique()

array([1440, 1080, 1242,  828, 1125,  750,  720,  240, 2160,  640, 1600,
        768, 1520,  540,  480, 1280,  850,  560,  360,  600, 1176,  400,
       1536, 1880,  854,  800, 1024,  320])

In [17]:
data['resolution_y'].unique()

array([3120, 2400, 2688, 1792, 2340, 3040, 2436, 2960, 2160, 2240, 2280,
       2246, 2560, 1334, 1920, 2880, 1280, 1600, 1560, 2520, 2248, 1520,
       2310, 2220, 2244, 2316, 1440,  320, 3840, 1136, 1544, 1500,  720,
       1620, 1480, 1080,  960,  854,  800,  480, 3200, 2636, 1548, 2152,
       2270, 1580, 1498, 1290,  640, 1820,  584,  600,  485])

In [18]:
data['processor'].unique()

array([ 8,  6,  1,  4, 10,  2])

In [19]:
data['ram_(mb)'].unique()

array([12000,  6000,  4000,  8000,  3000,  2000,   512,  1000,    64,
         384,   289,   256,   768])

In [20]:
data['internal_storage_(gb)'].unique()

array([2.56e+02, 6.40e+01, 1.28e+02, 3.20e+01, 1.60e+01, 8.00e+00,
       4.00e+00, 6.40e-02, 1.60e-01, 3.00e+00, 1.28e-01, 5.12e-01,
       5.12e+02, 2.00e+00, 1.00e+00])

In [21]:
data['rear_camera'].unique()

array([ 48. ,  64. ,  12. ,  16. ,  40. ,  12.2,  13. ,  12.3,  23. ,
        21. ,  32. ,  24. ,  20. ,  19. ,   2. ,  18. ,   8. ,  20.7,
         5. ,  10. ,  13.1,   8.7,   3. ,  41. ,   3.2, 108. ,  25. ,
         0. ,  21.5,   0.3,  15. ,  13.2])

In [22]:
data['front_camera'].unique()

array([16. , 12. , 32. , 10. , 24. , 20. , 25. , 13. ,  8. ,  7. ,  5. ,
        4. , 48. ,  0.3,  1.2,  2. ,  2.2,  3.7,  1.9,  1.3,  2.1,  2.4,
        0.9,  1.6,  0. ,  3. ,  1.1,  1.5,  3.2, 40. ])

In [23]:
data['operating_system'].unique()

array(['Android', 'iOS', 'Cyanogen', 'BlackBerry', 'Windows', 'Tizen',
       'Sailfish'], dtype=object)

In [24]:
data['number_of_sims'].unique()

array([2, 1, 3])

In [25]:
data['price'].unique()

array([ 58998,  27999, 106900,  62900,  49990,  34930,  52990,  79699,
        37999,  23190,  23990,  14999,  19282,  39995,  36990,  13999,
        54280,   9799,  63990,  29999,  31999,  45499,  69999,  59999,
        47990,  56999,   9990,  34999,  18999,   9349,  12000,  26999,
        49999,  36999,  47000,  20999,  53990,  14994,  30000,  26994,
        19999,  16999,  30990,  20246,  22999,  44999,  24999,  39996,
        23999,   6994,  42998,  25990,   5995,   7299,  25999,   3999,
         7999,   6999,  15999,  39999,   8999,  38999,  21150,  10990,
         9999,  26220,  47999,  12999,  15990,  23100,  15377,  16650,
        11999,   8600,  12990,  11845,  16879,   8649,  13690,  35999,
        11990,  22299,  39990,  17973,   9699,   7332,   9499,  25120,
        30999,  18000,  22000,  11900,  11770,  16490,   9580,  14990,
        21299,  59090,  18011,  10299,   8990,  16990,  18990,  18290,
         8849,  15899,  15900,  10499,  28499,   6990,  34990,  12994,
      

Changing currency from Rupees to euros and rounding them up

In [26]:
data['price'] = data['price']*0.012

In [27]:
data['price'] = data['price'].round(2)

In [28]:
def format_value(val):
    return '{:.2f}'.format(val)

data['price'] = data['price'].map(format_value)

In [29]:
data['price'].unique()

array(['707.98', '335.99', '1282.80', '754.80', '599.88', '419.16',
       '635.88', '956.39', '455.99', '278.28', '287.88', '179.99',
       '231.38', '479.94', '443.88', '167.99', '651.36', '117.59',
       '767.88', '359.99', '383.99', '545.99', '839.99', '719.99',
       '575.88', '683.99', '119.88', '419.99', '227.99', '112.19',
       '144.00', '323.99', '599.99', '443.99', '564.00', '251.99',
       '647.88', '179.93', '360.00', '323.93', '239.99', '203.99',
       '371.88', '242.95', '275.99', '539.99', '299.99', '479.95',
       '287.99', '83.93', '515.98', '311.88', '71.94', '87.59', '311.99',
       '47.99', '95.99', '83.99', '191.99', '479.99', '107.99', '467.99',
       '253.80', '131.88', '119.99', '314.64', '575.99', '155.99',
       '191.88', '277.20', '184.52', '199.80', '143.99', '103.20',
       '155.88', '142.14', '202.55', '103.79', '164.28', '431.99',
       '143.88', '267.59', '479.88', '215.68', '116.39', '87.98',
       '113.99', '301.44', '371.99', '216.00', '

In [32]:
data.to_csv('../Data_bases/data_for_clustering.csv', index=False)